services:
  - type: web
    name: Vylarc
    runtime: python
    repo: https://github.com/zandervanniekerk3101/Vylarc
    plan: free
    region: frankfurt
    branch: main
    buildFilter:
      paths:
      - src/**
      - requirements.txt
    buildCommand: pip install -r requirements.txt && alembic upgrade head
    
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /system/status
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vylarc-db
          property: connectionString
      - key: FLASK_SECRET_KEY
        sync: false 
      - key: ENCRYPTION_KEY
        sync: false 
      - key: GEMINI_API_KEY
        sync: false 
      - key: OPENAI_API_KEY
        sync: false 
      - key: PUBLIC_BASE_URL
        sync: false 
      - key: PYTHON_VERSION
        value: 3.11.5

databases:
  - name: vylarc-db
    databaseName: vylarc
    plan: free
    region: frankfurt
    ipAllowList: []